erDiagram
    RESTAURANTE ||--|{ CARDAPIO_ITEM : possui
    RESTAURANTE ||--o{ PEDIDO : recebe
    RESTAURANTE ||--o{ CAIXA_SESSAO : gerencia

    CLIENTE ||--o{ PEDIDO : realiza
    
    PEDIDO ||--|{ PEDIDO_ITEM : contem
    CARDAPIO_ITEM ||--o{ PEDIDO_ITEM : referencia
    
    PEDIDO ||--|| PAGAMENTO : liquida
    PEDIDO ||--o| DOCUMENTO_FISCAL : emite
    PEDIDO ||--o| DESPACHO_ENTREGA : encaminha
    
    ENTREGADOR ||--o{ DESPACHO_ENTREGA : executa

    RESTAURANTE {
        uuid id PK
        string cnpj UK
        string razao_social
        string nome_fantasia
        string timezone
    }

    CLIENTE {
        uuid id PK
        string nome
        string telefone UK
        string cpf
    }

    PEDIDO {
        uuid id PK
        uuid restaurante_id FK
        uuid cliente_id FK
        string codigo_diario
        string origem_canal "WEB_PROPRIO | IFOOD | PDV_LANCADOR"
        string status "CRIADO | PREPARO | PRONTO | DESPACHADO | ENTREGUE | CANCELADO"
        decimal valor_produtos
        decimal taxa_entrega
        decimal valor_total
        timestamp criado_em
    }

    PEDIDO_ITEM {
        uuid id PK
        uuid pedido_id FK
        uuid cardapio_item_id FK
        string nome_snapshot
        int quantidade
        decimal preco_unitario
        string observacoes
    }

    PAGAMENTO {
        uuid id PK
        uuid pedido_id FK
        string metodo "PIX | CARTAO_CREDITO | DINHEIRO"
        decimal valor_bruto
        decimal taxa_gateway
        decimal split_restaurante
        decimal split_entregador
        string status_transacao
    }

    DOCUMENTO_FISCAL {
        uuid id PK
        uuid pedido_id FK
        string chave_acesso UK
        string numero_nf
        string status "AUTORIZADA | CONTINGENCIA | CANCELADA"
        string xml_storage_url
        timestamp autorizado_em
    }

    DESPACHO_ENTREGA {
        uuid id PK
        uuid pedido_id FK
        uuid entregador_id FK
        string status "ALOCADO | EM_ROTA | ENTREGUE | EXTRAVIADO"
        string codigo_confirmacao
        timestamp saida_em
        timestamp entrega_em
    }

    CAIXA_SESSAO {
        uuid id PK
        uuid restaurante_id FK
        uuid operador_id
        timestamp abertura_em
        timestamp fechamento_em
        decimal saldo_inicial
        decimal total_entradas_declaradas
        decimal total_entradas_sistema
        decimal diferenca_apurada
    }
